# Copyright 2025 Rainer Gerhards and Others
#
# https://github.com/rsyslog/rsyslog-pkg-ubuntu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: yamllint check

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Identify changed YAML files
        id: changed
        uses: tj-actions/changed-files@v46
        with:
          files: |
            **/*.yml
            **/*.yaml

      - name: Install yamllint
        if: steps.changed.outputs.any_changed == 'true'
        run: pip install yamllint

      - name: Run yamllint
        if: steps.changed.outputs.any_changed == 'true'
        run: |
          yamllint -d relaxed ${{ steps.changed.outputs.all_changed_files }}

      - name: Skip yamllint, no YAML changes
        if: steps.changed.outputs.any_changed != 'true'
        run: echo "No YAML files modified"
